server:
  port: 9001
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eteration
    username: eteration
    password: bootcamp
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-master.xml
  cache:
    host: localhost
    port: 6379
    time-to-live: 600000
    redis:
      key-prefix: jdj
eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8080/eureka/}