server:
  port: 9002
spring:
  application:
    name: event-service
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: eteration
      password: bootcamp
      database: eteration
      host: localhost
      port: 27017
  cache:
    host: localhost
    port: 6379
    time-to-live: 600000
    redis:
      key-prefix: evt
eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8080/eureka/}