server:
  port: 5020
spring:
  application:
    name: mentorship-service
  datasource:
    url: jdbc:mysql://localhost:6001/mentorship
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: false
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    enabled: false
    change-log: classpath:/db.changelog-master.xml
  cache:
    host: localhost
    port: 6002
    time-to-live: 600000
    redis:
      key-prefix: mnt
eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:5001/eureka/}