version: '3.8'

services:
  auth-db:
    image: postgres:13.3
    container_name: auth
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: fnkaya
      POSTGRES_PASSWORD: fnkaya
    ports:
      - '6000:5432'
  mentorship-db:
    image: mysql:5.7
    container_name: mentoship
    restart: always
    ports:
      - '6001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      services:

#  redis:
#    image: redis:6.2.4
#    container_name: redis
#    restart: always
#    ports:
#      - '6002:6379'

#  mongo-db:
#    image: mongo:4.0.9
#    container_name: mentorship-mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: fnkaya
#      MONGO_INITDB_ROOT_PASSWORD: fnkaya
#    ports:
#      - '6001:27017'