version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: eteration
      POSTGRES_USER: eteration
      POSTGRES_PASSWORD: bootcamp
    ports:
      - '5432:5432'
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
